title: Sergey Kim
description: Senior software engineer (Android, Kotlin)
- **Email:** sergey.lvovich.kim@gmail.com
- **Phone:** +821024554709
- **LinkedIn:** [linkedin.com/in/sergeykim](https://www.linkedin.com/in/sergey-kim-58825a1a0/)
- **GitHub:** [github.com/slvkim](https://slvkim.github.io/)
- **Website:** [https://slvkim.github.io/](https://slvkim.github.io/)
theme: jekyll-theme-minimal
